### ISSUE TITLE
fix tutorial 3

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/ilp-node#39]
intermittent:
```js
[michiel@mbp ~/gh/michielbdejong/ilp-node (master *)]$ node scripts/flood.js 1 clp clp
[ '/Users/michiel/.nvm/versions/node/v7.7.1/bin/node',
  '/Users/michiel/gh/michielbdejong/ilp-node/scripts/flood.js',
  '1',
  'clp',
  'clp' ]
flooder open, flooding
tried to find curve peer.testing.ab833ece33938b2327b0d7ab78a28a39c498c9915e8ab05026d5400f0fa2da34.downstream_undefined.hi { 'test.crypto.xrp.':
   { buf: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ff ff 00 00 00 00 00 00 ff ff>,
     peer: 'ledger_xrp' },
  'peer.testing.52a46a3834686ed9b9d6bb12d6cad8a3c0cedf92a430e6f2b5d2b8841c615815.upstream_wssamundsenmichielbdejongcom.':
   { buf: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ff ff 00 00 00 00 00 00 ff ff>,
     peer: 'upstream_wssamundsenmichielbdejongcom' } }
/Users/michiel/gh/michielbdejong/ilp-node/src/quoter.js:72
    throw new Error('no curve found')
    ^

Error: no curve found
    at Quoter.findCurve (/Users/michiel/gh/michielbdejong/ilp-node/src/quoter.js:72:11)
    at Quoter.findHop (/Users/michiel/gh/michielbdejong/ilp-node/src/quoter.js:105:24)
    at Forwarder.forward (/Users/michiel/gh/michielbdejong/ilp-node/src/forwarder.js:22:54)
    at IlpNode.handleTransfer (/Users/michiel/gh/michielbdejong/ilp-node/src/index.js:227:43)
    at Peer._handleIlp (/Users/michiel/gh/michielbdejong/ilp-node/src/peer.js:27:19)
    at Clp.handleProtocolRequest (/Users/michiel/gh/michielbdejong/ilp-node/src/clp.js:299:49)
    at Clp.incoming (/Users/michiel/gh/michielbdejong/ilp-node/src/clp.js:164:14)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/Users/michiel/gh/michielbdejong/ilp-node/node_modules/ws/lib/WebSocket.js:143:47)

**Comment by michielbdejong** [comment]
fixed in 3.3.0
